
spring:
  datasource:
    url: jdbc:postgresql://db:5432/dbacademia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: admin
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
