server.port: 8088

spring:
  datasource:
    url: jdbc:postgresql://db:5432/db_academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
    username: admin
    password: p123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace